default: &default
  adapter: mysql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: lkj_development

test:
  <<: *default
  database: lkj_test

production:
  <<: *default
  database: lkj_production
  username: lkj
  password: <%= ENV["LKJ_DATABASE_PASSWORD"] %>
